<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEki5EPa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEki5EPa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEki5EPa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEki5EPa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEki5EPa\App_KernelDevDebugContainer([
    'container.build_hash' => 'Eki5EPa',
    'container.build_id' => '68ce148f',
    'container.build_time' => 1704813929,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEki5EPa');
